import { SignUp } from "@/features/auth/ui/SignUp";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Зарегистрироваться",
  description: "Generated by create next app",
};

export default function Page() {
  return <SignUp />;
}
