import { createClient } from "@/app/supabase/server";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { SignUp } from "@/features/auth";

export const metadata: Metadata = {
  title: "Зарегистрироваться",
  description: "Generated by create next app",
};

export default async function Page() {
  const supabase = await createClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (session) {
    redirect("/");
  }

  return <SignUp />;
}
