import { getSession } from "@/entities/auth/api";
import { SignIn } from "@/features/auth/ui/SignIn";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Войти в систему",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await getSession();
  if (session) {
    redirect("/");
  }

  return <SignIn />;
}
